services:
  postgres:
    container_name: postgres_container
    image: postgres
    restart: always
    env_file:
      - .env

    ports:
      - "5432:5432"
    volumes:
      - ./docker-volumes/postgres:/var/lib/postgresql/data
